### ISSUE TITLE
New design on NotificationTemplate

### ISSUE THREAD

**Issue by eugapx** [djangoflow/django-df-notifications#4]
In the current design, we handle all notification channels via [NotificationTemplate class](https://github.com/djangoflow/django-df-notifications/blob/main/df_notifications/models.py#L57). 

It's bad because different [channels](https://github.com/djangoflow/django-df-notifications/blob/main/df_notifications/models.py#L20) require different fields: email needs a subject, body, body_html; push needs a subject, body, data.

Also, we handle sending notifications to the different channels in one [place](https://github.com/djangoflow/django-df-notifications/blob/main/df_notifications/models.py#L98).

We need to develop a design, that allows us to write separate handlers (classes I think) for different notification channels. 

Something like this, but you can propose your own solution for these problems:

 ```
 class BaseNotificationChannel:
    parts = []
  
    def render_parts(...):
        return {p: ... for p in self.parts}

  
class EmailNotificationChannel(BaseNotificationChannel):
    parts = ['subject', 'body', 'body_html']
    

    def send(...):
        parts = self.render_parts(...)
        send_email(...)
```

To store template parts in the DB, we can use https://github.com/jazzband/django-dbtemplates. Also, we need to lookup up the templates in the `template` folder if we find none in the DB.

NotificationTemplate instances will store links or paths to these parts in this case.

**Comment by ayushin** [comment]
Yes, I also think the templates should follow a pattern like {prefix}_{channel}_{part}.{type}

i.e.
`/accounts/notifications/signup_email_body.html`
