### ISSUE TITLE
[Tests] Add a unit test for JSONPostWebhookChannel

### ISSUE THREAD

**Issue by eugapx** [djangoflow/django-df-notifications#7]
Add a test to the [tests.py](https://github.com/djangoflow/django-df-notifications/blob/main/tests/test_app/tests.py) for the [JSONPostWebhookChannel.send](https://github.com/djangoflow/django-df-notifications/blob/main/df_notifications/channels.py#L69) method.

The goal is to check that we send correct http payload using `JSONPostWebhookChannel` channel.

**Comment by ersul4ik** [comment]
hi @eugapx, what do u think about [https://github.com/djangoflow/django-df-notifications/blob/main/tests/test_app/tests.py#L320](test_json_post_webhook_channel) ?

btw, there should be a validation to check that `context` contains all required `template_parts`

**Comment by eugen1j** [comment]
@eugapx test

**Comment by eugen1j** [comment]
@eugapx test
